version: '3.8'
services:
  db:
     image: postgres:13.7-alpine
     container_name:
       shareit-db
     ports:
       - "6541:5432"
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - TZ=EUROPE/MOSCOW
  server:
    build: ./server
    image: shareit-server
    container_name: server
    environment:
      - TZ=EUROPE/MOSCOW
    ports:
      - "9090:9090"
    depends_on:
      - db

  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
