version: '3.8'
services:
  db:
     image: postgres:13.7-alpine
     container_name:
       shareit-db
     ports:
       - "6541:5432"
     environment:
       - DB_NAME=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=root
       - DB_HOST=localhost
       - DB_PORT=5432
  server:
    build: ./server
    image: shareit-server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DATASOURCE_LOGIN=postgres
      - DATASOURCE_PASSWORD=root
  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090


