CREATE TABLE IF NOT EXISTS Items
(
    ID           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    USER_ID      INT                                              NOT NULL,
    IS_AVAILABLE BOOL                                             NOT NULL,
    DESCRIPTION  VARCHAR DEFAULT ('Enter Description here.'),
    NAME         VARCHAR(64)                                      NOT NULL
);

CREATE TABLE IF NOT EXISTS Users
(
    ID    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    NAME  VARCHAR                                          NOT NULL,
    EMAIL VARCHAR(128),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Bookings
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    OWNER_ID  INT                                                 NOT NULL,
    BOOKER_ID INT                                                 NOT NULL,
    START_TIME     DATETIME                                            NOT NULL,
    END_TIME       DATETIME                                            NOT NULL,
    STATE     INT                                                 NOT NULL
);